#spring.profiles.include=oauth
#spring.jpa.show_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.h2.console.enabled=true
#spring.session.store-type=jdbc

spring:
  jpa:
    show_sql: true
    properties:
      hibername:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

